version: '3'
services:
    ic-webappnew:
        container_name: ic-webappnew
        ports:
            - "11000:8080"
        environment:
              "ODOO_URL": "http://${HOST_IP}:8069/"
              "PGADMIN_URL": "http://${HOST_IP}:8080/"
        image: 'ic-webapp:1.0'
        networks:
            - ic-network

networks:
  ic-network:
    driver: bridge


